# Exercícios Numpy

<b></b>
A biblioteca Numpy é uma biblioteca numérica do Python para arrays multidimensionais.É muito importante para computação científica no Python, pois suporta operações com vetores e matrizes multidimensionais de alta performance, além de várias ferramentas para se trabalhar com essas matrizes.

<a name="top"></a>Conteúdo
===

- [Criando um array numpy](#Criando_Array_Numpy)
- [Fatiamento (slice) de array](#Fatiamento_Array)
    - [Fatiamento em array unidimensional](#Fatiamento_unidimensional)
    - [Fatiamento em arrays multidimensionais](#Fatiamento_multidimensional)
- [Ordenamento de Arrays](#Ordenamento_Array)
- [Agregações: Min, Max, etc..](#Agregacoes_Array)
    - [Somando os valores em um array](#Somando_Array)
    - [Minimo_e Maximo](#Minimo_Maximo)
    - [Funções agregadas em arrays multidimensionais](#Agregadas)
    - [Exercicios](#Exercicios)
    - [Desafio 1](#Desafio1)
- [Operações aritméticas em arrays](#Operacoes_Aritmeticas)
    - [Multiplicação de Matrizes](#Multiplicação)
    - [Operadores de comparação](#Operadores)
    - [Elementos Distintos em Arrays](#Distintos)
    - [Contagem](#Contagem)
    - [Revisitando o Desafio 1](#Revisita)
    - [Exercícios](#Exercicios1)
    - [Operadores booleanos](#Booleanos)
    - [Seleção em matrizes booleanas](#Selecao_Booleana)
    - [Desafio 2](#Desafio2)

Para se trabalhar com a biblioteca NumPy é necessário realizar sua importação.

In [2]:
import numpy as np

<a id="Criando_Array_Numpy"></a> 
Criando um array numpy. 
---
Um array numpy é um conjunto de variáveis que armazenam valores do mesmo tipo. Semelhantemente as lista Python, o acesso aos valores do array é efetuado através de índices inteiros não negativos. Os arrays podem ser uni (1D), bi(2D), ... dimensionais.
A criação de arrays pode ser efetuada de várias maneiras. A maneira mais simples é através da função **``np.array(lista/tupla)``**. As dimensões das matrizes são dadas no momento da criação, isto é, o número de dimensões do array é dado pela informação do tamanho de cada dimensão. Pesquise as diferentes formas de criação de arrays NumPy:
1. matriz vazia (empty) - utiliza-se a função.**``np.empty(dimensões/tamanho)``**
2. matriz incializada com zeros - utiliza-se a função. **``np.zeros(dimensões/tamanho)``**
3. matriz inicializada com o valor 1 - utiliza-se a função. **``np.ones(dimensões/tamanho)``**
4. com x elementos de um valor inicial até final - utiliza-se a função. **``np.array(Range(tamanho ou intervalo))``** ou **``np.arange([inicio],fim,[tamanho intervalo])``**
5. matriz inicializada com valores booleanos. **``np.ones (tamanho,dtype=bool)``** ou **``np.full(dimensão,preenchimento,dtype=bool)``**
6. matriz inicializada com valores dentro de um intervalo, distribuídos uniformemente. **``np.linspace(inicio,fim,tamanho intervalo)``**
7. matriz identidade - matriz quadrada inicializada com zeros exceto na diagonal formada por 1's. **``np.identity(ordem da matriz)``**.
8. Matriz eye - cria uma matriz identidade bidimensional. **``np.eye(linhas, colunas)``**
9. matriz full - Cria uma matriz com valor de preenchimento dado. **``np.full(dimensão, valorpreenchimento)``**

Crie 6 arrays unidimensionais - 1D (Vetor) com 10 elementos cada:<br>
    1. sem inicialização (empty)
    2. inicializa todos elementos com valor zero (zeros)
    3. inicializar todos elementos com valor 1 (ones)
    4. inicializar com números de 1 a 10 (array)
    5. inicializar com valor True (full com dtype = bool)
    6. inicializar com valores entre 1 e 10 com 6 elementos espaçados uniformente (linspace).
    OBS: Mostre os vetores criados

In [36]:
# Coloque seu código Aqui
vazio = np.empty(10) #sem inicialização (empty)
print('vazio = ', vazio, '\n')

zero = np.zeros(10) # inicializa todos elementos com valor zero
print('zeros = ', zero, '\n')

ums = np.ones(10) # inicializar todos elementos com valor 1 
print('Ums = ', ums, '\n')

dez = np.array(range(1,11)) # inicializar com números de 1 a 10
print('dez = ', dez, '\n')

boole = np.full([10], 1, dtype = bool) # inicializar com valor True
print('boole = ', boole, '\n')

lin = np.linspace(1,10, 6) # inicializar com valores entre 1 e 10 com 6 elementos espaçados uniformente
print('lin = ', lin, '\n')

# Extra
ara = np.arange(1,15, 1.5) # inicializar com valores entre 1 e 10 com 6 elementos espaçados uniformente
print('ara = ', ara, '\n')

vazio =  [ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13.  14.5] 

zeros =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

Ums =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

dez =  [ 1  2  3  4  5  6  7  8  9 10] 

boole =  [ True  True  True  True  True  True  True  True  True  True] 

ara =  [ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13.  14.5] 

lin =  [ 1.   2.8  4.6  6.4  8.2 10. ] 



Crie 4 arrays bidimensionais-2D (matriz) com 3 linhas e 4 colunas (3X4):
    1. inicializada com zeros (função full)
    2. inicializada com 1's
    3. inicializada com valor booleano False
  

In [30]:
#Coloque seu código aqui
ums2d = np.full([3,4], 0, dtype = int) # inicializar com valor zeros
print('ums2d = ', ums2d, '\n')

one2d = np.ones([3,4]) # inicializar com valor 1
print('one2d = ', one2d, '\n')

bool2d = np.full([3,4], 0, dtype = bool) # inicializar com valor True
print('boole = ', bool2d, '\n')

ums2d =  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

one2d =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

boole =  [[False False False False]
 [False False False False]
 [False False False False]] 



Crie 2 matriz quadrada 4X4 com os valor 1 na diagonal (use as funções np.identity e np.eye)

In [52]:
# Coloque seu código aqui

id2d = np.identity(4) # inicializar com valor 1 na diagonal
print('id2d= ', id2d, '\n')

ey2d = np.eye(4, k=0) # inicializar com valor 1 na diagonal k = 0 (diag. principal), k = -1 abaixo da dig e k = 1 acima
print( ey2d, '\n')

id2d=  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



Dada a matriz abaixo, exiba os valores da diagonal da matriz (np.diag)

In [39]:
mat = [[1,2,3,4],
       [5,6,7,8],
       [8,7,6,5],
       [4,3,2,1]]

#Coloque seu código aqui
dia = np.diag(mat)
print('dia = ', dia)

dia =  [1 6 6 1]


[voltar ao topo](#top)

<a id="Fatiamento_Array"></a> Fatiamento (slice) de array
---
Para acessarmos partes do array utilizamos a notação *slice*, marcada pelo caractere de dois pontos (**``: ``**) para representar o intervalo do array que se quer acessar.

A sintaxe de fatiamento NumPy segue a da lista padrão do Python; para acessar uma fatia do **``array``**, use o seguinte:

**``
array[inicio : fim : passo]
``**
<br><br>Se algum desses itens não for especificado, eles serão padronizados com os valores **`` inicio = 0``, `` fim = tamanho da dimensão`` , ``passo = 1``**.

Vamos analisar o acesso a sub-matrizes em uma dimensão e em várias dimensões.

<a id="Fatiamento_unidimensional"></a> 
### Fatiamento em array unidimensional

In [53]:
arr = np.arange(10, 34, 2)  # Cria o array arr iniciando em 10 incrementando de 2 unidades até o 34
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [54]:
arr[:4]  # primeiros quatro elementos


array([10, 12, 14, 16])

In [55]:
arr[5:] # exibe a partir do 6º elemento até o final


array([20, 22, 24, 26, 28, 30, 32])

In [60]:
arr[1::2] # exibe os elementos espaçados de 2 em 2 posições, a partir da  posição 2 até o fim do array.


array([12, 16, 20, 24, 28, 32])

Um caso particularmente interessante é quando o passo é negativo. Nesse caso, os padrões para iniciar e parar são trocados. Isso se torna uma maneira conveniente de reverter uma matriz:

In [61]:
arr[::-1]  # exibe todos os elementos na ordem inversa


array([32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10])

In [62]:
arr[5::-2]  # exibe os elementos a partir do índice 5, de -2 em -2,até 


array([20, 16, 12])

<a id="Fatiamento_multidimensional"></a> 
### Fatiamento em arrays multidimensionais

O fatiamento em arrays multidimensionais acontece do mesmo modo, com exceção de que você deverá fazer o fatiamento por dimensão.

In [64]:
arr = arr.reshape((4,3)) #Redimensiona o array para 5 linhas x 2 colunas
arr

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32]])

In [10]:
arr[:2,:2] # exibe o array com 2 linhas e 2 colunas

In [11]:
arr[:-1,:-1] #Exibe da 1 linha até a penúltima e da 1 coluna até a penúltima

[voltar ao topo](#top)

 <a id="Ordenamento_Array"></a> 
Ordenamento de Arrays
---

Ordenamento de arrays permite clssificar (ordenar) os elementos de um array, de modo ascendente ou descente. O objeto NumPy ndarray possui uma função **``np.sort(array, axis=0/1)``**, que classifica uma matriz especificada. O **``axis``** é usado para matriz multidimensionais para indicar se a ordenação é 0 por coluna ou 1 por linha.<br>
Para realizar a classificação em ordem descendente, use:  **``-np.sort(-array)``**

In [69]:
# Classifique o array 1D (em linha) em ordem ascendente (sort)
ar1 = np.array([1,8,-4, 3, -1, 7])

#Coloque seu código aqui

ar1.sort()
print(ar1,'\n')

# # Classifique o array 2D (em linha) em ordem ascendente (sort)
ar2 = np.array([[8,-4, 3, -1, 7], [6, 8, 5, 4,-1]])

#Coloque seu código aqui

ar2.sort(axis=1)
print(ar2)


[-4 -1  1  3  7  8] 

[[-4 -1  3  7  8]
 [-1  4  5  6  8]]


In [72]:
# Classifique o Array unidimensional (em linha) em ordem descendente (ordem inversa)

ar1 = np.array([8, 9, 10, 7, 11])

#Coloque seu código aqui
ar1 = -np.sort(-ar1)
print(ar1)

[11 10  9  8  7]


<a id="Agregacoes_Array"></a> 
Agregações: Min, Max, etc..
---
Muitas vezes, quando confrontados com uma grande quantidade de dados, um primeiro passo é calcular estatísticas sumárias para os dados em questão.
Talvez as estatísticas sumárias mais comuns sejam o desvio médio e padrão, que permitem resumir os valores "típicos" em um conjunto de dados, mas outros agregados também são úteis (a soma, produto, mediana, mínimo e máximo, quantiles, etc.).

O NumPy tem funções rápidas de agregação incorporadas para trabalhar em arrays:


[voltar ao topo](#top)

<a id="Somando_Array"></a> 
## Somando os valores em um array

Um rápido exemplo: considere calcular a soma de todos os valores em um array. 
O próprio Python pode fazer isso usando a função **``sum``** incorporada:
+ **sum(array)** - Função soma do python
+ **numpy.sum(array)** - Função soma Numpy

In [73]:
arr = np.random.random(100)    #Cria randomicamente 100 números em um array numpy
x = sum(arr)     # Função soma do Python
print(x, '\n')

x = np.sum(arr)     # Função soma do NumPy
print(x)


51.56363526311981 

51.56363526311979


<a id="Minimo_Maximo"></a> 
## Mínimo e Máximo

Da mesma forma, o Python possui funções incorporadas  **``min``  e  ``max``** , usadas para encontrar o valor mínimo e o valor máximo de qualquer matriz:
+ **min(array) e max(array)** - Funções mínimo e máximo do python
+ **numpy.min(array) e numpy.max(array)**  - Funções mínimo e máximo do Numpy

obs:np.random.randint(início,fim, (qtd_arr, lin, col)) #Gera qtd_arr matrizes lin,col aleatoriamente de números inteiros

In [5]:
#Criar randomicamente um array numpy com 100 números e mostre o maior e o menor elemento do vetor criado
#Coloque seu código aqui
aleat = np.random.randint(1, 100, (1, 100))  # usar o módulo randint 1D
print(aleat)
maior =aleat.max() 
print('maior = ', maior, '\n')
menor =aleat.min() 
print('menor = ', menor, '\n')
#####################
aleat = np.random.randint(1, 100, (1, 3, 3))  # usar o módulo randint 2D
print(aleat)
maior =aleat.max() 
print('maior = ', maior, '\n')
menor =aleat.min() 
print('menor = ', menor, '\n')



[[41 40 10 33 44 57 55 83 73  5 87 83 91 88 28 72 79 99 29 11 95 57 18 61
  64 80 52 67 91 11 76 80 48 58 22 46 64 93 97 31 56 53 23  3 95 46 37  6
  68 70 22  2 17 29 42 31 24 37  6 99 22  2 10 43 88 51 72 17  5  8 82 93
  35 18 49 32 91 24  5  4 48 49 44 70 33 22 78 74 43 11  5 59 87 13  8  3
  96 66 65 66]]
maior =  99 

menor =  2 

[[[64 98 93]
  [93 89 93]
  [87 67 18]]]
maior =  98 

menor =  18 



[voltar ao topo](#top)

<a id="Agregadas"></a> 
## Funções agregadas em arrays multidimensionais

É possivel o uso de funções agregadas em arrays multidimensionais. Nesse tipo de arrays a operação de agregação pode ser aplicada ao array como um todo, mas também podemos aplicá-las ao longo de uma linha ou coluna, para isso utilizamos o argumento axis = 0 ou -1 para coluna e axis= 1 para linhas.

Podemos randomicamente um array bidimensional 3X3 e mostrar a soma do array como um todo, ao longo das linhas e das colunas. Mostre os valores encontrados.

In [14]:
#Criar um array randomico bidimensional 3X3 Float
arr = np.random.random(9).reshape((3, 3)) #A função reshape() redimensiona o array 1D para um array 2D
print(arr,'\n')
#Somar todos os elementos do array
print(arr.sum(),'\n')

#Somar todas as colunas do array
print(arr.sum(axis=-1),'\n')

#Somar todas as linhas do array
print(arr.sum(axis=1),'\n')

#####################
alea = np.random.randint(1, 100, (1, 3, 3))  # usar o módulo randint 2D

print(alea)

somalin = alea.sum(axis=1) 
print('somalin = ', somalin, '\n')

somacol = alea.sum(axis=-1) 
print('somacol = ', somacol, '\n')

#x = np.array([[12, 94, 18],
#  [11, 52, 31],
#  [29, 41, 37],
#  [80,  1, 71]])

#print(x.sum(axis=0))  

[[0.25715916 0.23375593 0.09326785]
 [0.47895139 0.43035333 0.56421807]
 [0.23753424 0.53518479 0.10797088]] 

2.93839563194321 

[0.58418293 1.47352278 0.88068991] 

[0.58418293 1.47352278 0.88068991] 

[[[76 57 37]
  [63 21  9]
  [90 43 34]]]
somalin =  [[229 121  80]] 

somacol =  [[170  93 167]] 



Como falado anteriormente, em arrays com mais de uma dimensão, as funções de agregação levam um argumento adicional especificando o eixo ao longo do qual o agregado é calculado. Por exemplo, podemos encontrar o valor mínimo dentro de cada coluna (axis=0/-1) ou cada linha(axis=1).


Criar randomicamente um array bidimensional 3X3 e mostrar os valores máximo e mínimo do array como um todo, ao longo das linhas e das colunas. Mostre os valores encontrados.

In [11]:
#Coloque seu código aqui

aleat = np.random.randint(1, 100, (1, 3, 3))  # usar o módulo randint 2D
#print(aleat)
maior =aleat.max() 
print('maior = ', maior, '\n')
menor =aleat.min()
print('menor = ', menor, '\n')

macol = aleat.max(axis=-1) 
print('maiorcol = ', macol, '\n')

micol = aleat.min(axis=-1) 
print('menorcol = ', micol, '\n')

malin = aleat.max(axis=1) 
print('maiorlin = ', malin, '\n')

milin = aleat.min(axis=1) 
print('menorlin = ', milin, '\n')

maior =  74 

menor =  5 

maiorcol =  [[74 28 71]] 

menorcol =  [[32 25  5]] 

maiorlin =  [[74 32 47]] 

menorlin =  [[26  5 28]] 



<a id="Outras_Funcoes"></a> 
### Outras funções de agregação

NumPy fornece muitas outras funções de agregação, mas não vamos discuti-las em detalhes aqui.

A tabela a seguir fornece uma lista de funções úteis de agregação disponíveis no NumPy: <br>


|   Função          |                  Descrição                         |
|-------------------|----------------------------------------------------|
| ``np.sum``        | Computa a soma dos elementos                       |
| ``np.prod``       | Computa o produto dos elementos                    |
| ``np.mean``       | Computa média dos elementos                        |
| ``np.std``        | Computa o desvio padrão                            |
| ``np.var``        | Computa a variança                                 |
| ``np.min``        | Encontra o menor valor                             |
| ``np.max``        | Encontra o maior valor                             |
| ``np.argmin``     | Encontra o índice do menor valor                   |
| ``np.argmax``     | Encontra o index do maior valor                    |
| ``np.median``     | Computa a mediana dos elementos                    |
| ``np.percentile`` | Computa estatísticas baseadas em rank de elementos |
| ``np.any``        | Avalia se ha algum elemento é verdadeiro           |
| ``np.all``        | Avalia se todos os elementos são verdadeiro        |




[voltar ao topo](#top)

<a id="Exercicios"></a> 
### <font color="red">Exercícios</font>

In [22]:
# Lista com os nomes dos presidentes
presidentes = ["Michel Temer","Getúlio Vargas","Artur da Costa e Silva","Nereu Ramos","Ernesto Geisel","Castelo Branco",
               "Augusto Rademaker","Emílio Garrastazu Médici","Aurélio de Lira Tavare","Jair Bolsonaro",
               "Fernando Henrique Cardoso","Márcio de Sousa Melo","Dilma Rousseff","Eurico Gaspar Dutra",
               "Itamar Franco","Deodoro da Fonseca","Carlos Luz","João Figueiredo","Augusto Tasso Fragoso",
               "José Linhares","Afonso Pena","Campos Sales","Luiz Inácio Lula da Silva","Washington Luís",
               "Isaías de Noronha","João Mena Barreto","Café Filho","Hermes da Fonseca","José Sarney","Rodrigues Alves",
               "Epitácio Pessoa","Ranieri Mazzilli","Juscelino Kubitschek","Prudente de Morais","Floriano Peixoto",
               "Ranieri Mazzilli","Delfim Moreira","Getúlio Vargas","Artur Bernardes","Venceslau Brás","Jânio Quadros",
               "João Goulart","Nilo Peçanha","Fernando Collor"]

# Numpy array com as idades correspondentes do presidente ao chegar à presidência.
idades = np.array([75, 68, 67, 67, 66, 66, 64, 63, 63, 63, 63, 
                    63, 63, 62, 62, 62, 61, 61, 61, 59, 58, 57, 57, 57, 56, 56, 55, 55, 54, 
                    54, 54, 53, 53, 53, 52, 51, 50, 48, 47, 46, 44, 42, 41, 40])


Exiba a média e o desvio padrão das Idades dos Presidentes do Brasil.

In [23]:
#Coloque seu código aqui

media = idades.mean()
print("media =", media, '\n')

std = idades.std()
print('Desvio Padrão = ', std)

media = 57.09090909090909 

Desvio Padrão =  7.739562419561004


Exiba os nomes dos presidentes mais novos e mais velhos que assumiram a presidência 

In [24]:
#Coloque seu código aqui
indnovo = idades.argmin()
indvelho = idades.argmax()
print(presidentes[indnovo], 'foi o presidente mais novo a assumir a presidência com', idades[indnovo], 'anos\n')
print(presidentes[indvelho], 'foi o presidente mais velho a assumir a presidência com', idades[indvelho], 'anos')

Fernando Collor foi o presidente mais novo a assumir a presidência com 40 anos

Michel Temer foi o presidente mais velho a assumir a presidência com 75 anos


Exiba o primeiro quartil (25%) e o terceiro quartil (75%) da amostra das idades

In [25]:
#Coloque seu código aqui
primeiro = np.percentile(idades,25)
print('primeiro = ',primeiro,'\n')
terceiro = np.percentile(idades,75)
print('terceiro= ', terceiro)

primeiro =  53.0 

terceiro=  63.0


[voltar ao topo](#top)

<a id="Desafio1"></a> 
### <font color="red">Desafio 1:</font>

Desenvolva um código que compute e exiba a frequência das idades dos ex-presidentes. 

In [51]:
#Coloque seu código aqui

freq = []
idad = []

for i in idades:
    if i in idad:
        freq[idad.index(i)] += 1
    else:
        idad.append(i)
        freq.insert(idad.index(i),1)
for j in range(len(idad)):
    if j % 2 == 0:
      x = ''
      x = x + str(idad[j])+': '+str(freq[j])
    else:    
      x = x + '     ' + str(idad[j]) + ': '+ str(freq[j])     
      print(x,'\n' )
        
if len(idad) % 2 == 1:
    print('         ',x,'\n')

75: 1     68: 1 

67: 2     66: 2 

64: 1     63: 6 

62: 3     61: 3 

59: 1     58: 1 

57: 3     56: 2 

55: 2     54: 3 

53: 3     52: 1 

51: 1     50: 1 

48: 1     47: 1 

46: 1     44: 1 

42: 1     41: 1 

          40: 1 



<a id="Operacoes_Aritmeticas"></a> 
Operações aritméticas em arrays
---
Adição, subtração, multiplicação e divisão são as operações aritméticas mais básicas na NumPy. Elas são semelhantes às operações aritméticas normais entre números, mas aplicadas a todos elementos do array. 

In [52]:
arr= np.array([5,7,9,11,13]) 

# Operaçoes aritméticas
print("arr     =", arr)
print("arr     =", -arr)      # Negação unária
print("arr + 5 =", arr + 5)   # Soma
print("arr * 2 =", arr * 2)   # Produto 
print("arr** 2 =", arr ** 2)  # Potenciação
print("arr / 2 =", arr / 2)   # Divisão 
print("arr// 2 =", arr // 2)  # quociente da divisão

arr     = [ 5  7  9 11 13]
arr     = [ -5  -7  -9 -11 -13]
arr + 5 = [10 12 14 16 18]
arr * 2 = [10 14 18 22 26]
arr** 2 = [ 25  49  81 121 169]
arr / 2 = [2.5 3.5 4.5 5.5 6.5]
arr// 2 = [2 3 4 5 6]


Os operadores aritméticos podem ser implementados por funções NumPy. A tabela abaixo exibe as funções aritméticas:

| Operador	    | Função Equivalente  |            Descrição                        |
|---------------|---------------------|---------------------------------------------|
|``+``          |``np.add``           |Adição (ex., ``1 + 1 = 2``)                  |
|``-``          |``np.subtract``      |Subtração (ex., ``3 - 2 = 1``)               |
|``-``          |``np.negative``      |Negação Unária (ex., ``-2``)                 |
|``*``          |``np.multiply``      |Multiplicação (ex., ``2 * 3 = 6``)           |
|``/``          |``np.divide``        |Divisão (ex., ``3 / 2 = 1.5``)               |  
|``//``         |``np.floor_divide``  |Quociente da divisão (ex., ``3 // 2 = 1``)   |
|``**``         |``np.power``         |Exponenciação (ex., ``2 ** 3 = 8``)          |
|``%``          |``np.mod``           |Resto (ex., ``9 % 4 = 1``)                   |


In [53]:
mat= np.array([[1,2,3,4],[2, 4, 6, 8], [5,7,9,11], [6, 7, 8, 9]]) 
print(mat,'\n')

# Criar a matriz transposta (.T) mat_t
mat_t = mat.T
print(mat_t,'\n')

#Usando as funções aritméticas Numpy para:
# Exibir a soma das duas matrizes
soma= mat + mat_t
print(soma,'\n')

# Exibir a subtração das duas matrizes
sub= mat - mat_t
print(sub,'\n')

# Exibir a multiplicação das matrizes
mult= mat * mat_t
print(mult,'\n')



[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 5  7  9 11]
 [ 6  7  8  9]] 

[[ 1  2  5  6]
 [ 2  4  7  7]
 [ 3  6  9  8]
 [ 4  8 11  9]] 

[[ 2  4  8 10]
 [ 4  8 13 15]
 [ 8 13 18 19]
 [10 15 19 18]] 

[[ 0  0 -2 -2]
 [ 0  0 -1  1]
 [ 2  1  0  3]
 [ 2 -1 -3  0]] 

[[ 1  4 15 24]
 [ 4 16 42 56]
 [15 42 81 88]
 [24 56 88 81]] 



[voltar ao topo](#top)

<a id="Multiplicação"></a> 
### Multiplicação de Matrizes

O símbolo **``* ``** efetua a multiplicação por elementos, não a multiplicação por matriz. Em vez disso, usamos a função **``dot ``** para calcular produtos internos de vetores, multiplicar um vetor por uma matriz e multiplicar matrizes. 

In [54]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([1,2])
w = np.array([3, 4])

# Produto interno dos vetores; ambos produzem 11
print(v.dot(w))
print(np.dot(v, w))

# Produto Matrix / vetor ; ambos produzem o array 1D [5 11]
print(x.dot(v))
print(np.dot(x, v))

# Produto Matrix / vetor ; ambos produzem o array 2D
# [[19 22]
#  [43 50]]

print(x.dot(y))
print(np.dot(x, y))

11
11
[ 5 11]
[ 5 11]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


[voltar ao topo](#top)

<a id="Operadores"></a> 
### Operadores de comparação

Na seção anterior vimos as funções e operadores aritméticos. Vimos que o uso de **``+``, ``-``, ``*``, ``/``,**  e outros em arrays que levam a operações em termos de elementos.
NumPy também implementa operadores de comparação como **``<`` (menor que) e ``>`` (maior que) etc**.
O resultado desses operadores de comparação é sempre uma matriz booleana. Uma matriz booleana é o resultado da aplicação de uma expressão relacional sobre o conjunto de dados da matriz. Os valores da matriz que atendem a expressão são representados pelo valor booleano True, do contrário False.

Todas as seis operações **(``<``, ``<=``, ``>``, ``>=``, ``==``, ``!=``)** de comparação padrão estão disponíveis:

In [55]:
x = np.arange(2,20,2)    # Cria o array com números pares de 2 a 18
print(x)
                  
print('\n\n', x < 6 )            # verifica quais elementos são menores que 6

print('\n\n',np.less_equal(x, 12))      # utilizando uma função numpy verifica quais elementos são menores ou iguais a 12

print('\n\n', x == 18 )            # verifica quais elementos são iguais a 18

[ 2  4  6  8 10 12 14 16 18]


 [ True  True False False False False False False False]


 [ True  True  True  True  True  True False False False]


 [False False False False False False False False  True]


 Um resumo dos operadores e as correspondentes funções Numpy de comparação. Pode-se usar ambos:
 
| Operador	    | Função equivalente  || Operador	   | Função equivalente  |
|---------------|---------------------||---------------|---------------------|
|``==``         |``np.equal``         ||``!=``         |``np.not_equal``     |
|``<``          |``np.less``          ||``<=``         |``np.less_equal``    |
|``>``          |``np.greater``       ||``>=``         |``np.greater_equal`` |
 

In [58]:
x =  np.random.randint(1,12,size=(4,3))  # Cria matriz 4X3 com números inteiros randomicos 
print(x)

# Verifica quais elementos são maiores ou iguais a 5. Mostre a matriz resultante
print('\n\n', x > 5)

# Verifica quais elementos são diferentes de 8. Mostre a matriz resultante

print('\n\n', np.not_equal(x,8))

[[11  4  3]
 [ 7  8  4]
 [ 9  4 11]
 [ 8  4 10]]


 [[ True False False]
 [ True  True False]
 [ True False  True]
 [ True False  True]]


 [[ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]]


[voltar ao topo](#top)

<a id="Distintos"></a> 
### Elementos Distintos em Arrays

A função **``np.unique(array, return_index=False, return_inverse=False, return_counts=False)``** retorna os elementos únicos (distintos) ordenados de uma matriz.
Existem três saídas opcionais, além da matriz com os elementos únicos:
+ os índices da matriz de entrada que dão os valores únicos (return_index)
+ os índices da matriz única que reconstroem a matriz de entrada (return_inverse)
+ o número de vezes que cada valor único aparece na matriz de entrada (return_counts)<br>

+ **Array 1D**

In [59]:
a1d = np.array([5,2,6,2,7,5,6,8,2,9]) 

a1d

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [60]:
# Retorna o array com valores distintos 
u = np.unique(a1d) 
print (u) 


[2 5 6 7 8 9]


In [61]:
# Retorna os valores distintos e seus índices no array original 
u,indices = np.unique(a1d, return_index = True) 
print(u, '\n')
print (indices) 


[2 5 6 7 8 9] 

[1 0 2 4 7 9]


In [62]:
# retorna a matriz de índices no array original 
u,indices = np.unique(a1d, return_inverse = True) 
print (u, '\n') 
print(indices)

#Reconstroi o array inicial
print(u[indices]) 


[2 5 6 7 8 9] 

[1 0 2 0 3 1 2 4 0 5]
[5 2 6 2 7 5 6 8 2 9]


In [63]:
#Retorna o array de contadores do número de vezes que cada elemento aparece repetido
u,indices = np.unique(a1d,return_counts = True)  
print (u) 
print (indices)


[2 5 6 7 8 9]
[3 2 2 1 1 1]


+ **Array 2D**

In [64]:
# Criação do array 2D
a2d =  np.random.randint(1,12,size=(4,3)) 
a2d


array([[ 6,  1,  9],
       [ 8,  4, 11],
       [ 1,  2, 11],
       [ 9,  3,  8]])

In [65]:
# Retorna o array da matriz 2D com elementos distintos
#Coloque seu código aqui
u = np.unique(a2d) 
print (u) 


[ 1  2  3  4  6  8  9 11]


In [66]:
# Exibir o array com os valores distintos e seus índices na matriz 2D original 
#Coloque seu código aqui
u,indices = np.unique(a2d, return_index = True) 
print(u, '\n')
print (indices) 


[ 1  2  3  4  6  8  9 11] 

[ 1  7 10  4  0  3  2  5]


In [67]:
# Exibir o array de índices do matriz 2D original 
#Coloque seu código aqui
u,indices = np.unique(a2d, return_inverse = True) 
print (u, '\n') 
print(indices)

#Reconstruir a matriz 2D original
#Coloque seu código aqui
print(u[indices]) 


[ 1  2  3  4  6  8  9 11] 

[4 0 6 5 3 7 0 1 7 6 2 5]
[ 6  1  9  8  4 11  1  2 11  9  3  8]


In [68]:
#Exibir o array de contadores do número de vezes que cada elemento aparece repetido
#Coloque seu código aqui
u,indices = np.unique(a2d,return_counts = True)  
print (u) 
print (indices)

[ 1  2  3  4  6  8  9 11]
[2 1 1 1 1 2 2 2]


<a id="Contagem"></a> 
### Contagem 

É a aplicação da função ``np.count_nonzero()`` sobre uma matriz booleana, com uma expressão relacional, para retornar a quantidade de valores True:

In [70]:
# x = [[11  4  3]
#     [ 7  8  4]
#     [ 9  4 11]
#     [ 8  4 10]]
# Exibe a quantidade de valores abaixo de 7
cont = np.count_nonzero(x < 7)
print(cont)

# Exibe a quantidade de valores maiores ou iguais a 3  por linha
cont= np.count_nonzero(x >= 3, axis=1)
print("\n",cont)

# Exibe a quantidade de valores iguais a 2  por coluna
cont= np.count_nonzero(x == 2, axis=0)
print("\n",cont)

[[11  4  3]
 [ 7  8  4]
 [ 9  4 11]
 [ 8  4 10]]
5

 [3 3 3 3]

 [0 0 0]


Se estamos interessados em verificar rapidamente se algum ou todos os valores são verdadeiros, podemos usar ```np.any``` ou ```np.all```:

In [71]:
# Existe algum valor em x maior 10
print(np.any(x > 10))

# Todos os elementos da matriz são menores que 10?
print(np.all(x < 10))

True
False


<a id="Revisita"></a> 
### <font color="red">Revisitando Desafio 1</font>
Reescreva o desafio 1 utilizando os novos conceitos aprendidos

In [72]:
# Coloque seu código aqui

idad,freq =np.unique(idades,return_counts = True)  


for j in range(len(idad)):
    if j % 2 == 0:
      x = ''
      x = x + str(idad[j])+': '+str(freq[j])
    else:    
      x = x + '     ' + str(idad[j]) + ': '+ str(freq[j])     
      print(x,'\n' )
        
if len(idad) % 2 == 1:
    print('         ',x,'\n')

40: 1     41: 1 

42: 1     44: 1 

46: 1     47: 1 

48: 1     50: 1 

51: 1     52: 1 

53: 3     54: 3 

55: 2     56: 2 

57: 3     58: 1 

59: 1     61: 3 

62: 3     63: 6 

64: 1     66: 2 

67: 2     68: 1 

          75: 1 



<a id="Exercicios1"></a> 
### <font color="red">Exercícios</font>
O array abaixo armazena as 288 leituras de temperaturas,realizadas a cada 5 minutos da 00:00 hora do dia 01/03/2020 até às 23:55 do mesmo dia, registradas em São Paulo. Desenvolva um código python para responder as seguintes perguntas:
1. Qual foi a média de temperatura do dia.
2. Qual foi a temperatura máxima registrada e em que hora ocorreu?
3. Qual foi a temperatura mínima registrada e em que hora ocorreu?
4. Qual o desvio-padrão e a variância das temperaturas?
5. Qual a mediana da amostra? <br>
OBS: Desenvolva uma função que possibilite calcular e retornar a hora da leitura, no formato: (hora,minuto)

In [85]:
temp = np.array([21.3, 21.3, 21.2, 21.2, 21.2, 21.1, 21, 20.9, 20.8, 20.8, 20.8, 20.7, 20.7, 20.7,
                 20.7, 20.7, 20.7, 20.7, 20.6, 20.6, 20.6, 20.6, 20.5, 20.4, 20.5, 20.5, 20.4, 
                 20.4, 20.4, 20.4, 20.3, 20.3, 20.3, 20.3, 20.2, 20.2, 20.2, 20.2, 20.2, 20.2, 
                 20.1, 20.1, 20.1, 20.1, 20.1, 20.1, 20.1, 20.1, 20.1, 20.2, 20.2, 20.2, 20.2, 
                 20.2, 20.2, 20.2, 20.3, 20.3, 20.4, 20.4, 20.4, 20.4, 20.3, 20.3, 20.4, 20.3, 
                 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 
                 20.3, 20.3, 20.3, 20.4, 20.4, 20.4, 20.5, 20.5, 20.6, 20.7, 20.7, 20.8, 20.9, 
                 21.1, 21.2, 21.4, 21.8, 22.1, 22.2, 22.2, 22.3, 22.4, 22.5, 22.6, 22.7, 22.8, 
                 23.1, 23.3, 23.4, 23.6, 23.8, 24.1, 24.5, 24.7, 24.6, 24.7, 24.9, 25.1, 25.3, 
                 25.4, 25.4, 25.8, 26.3, 26.3, 26.3, 26.3, 26.2, 26, 26, 26.3, 26.3, 26.5, 26.7, 
                 26.8, 27.1, 27.3, 27.2, 27.2, 27.3, 27.3, 27.2, 27.3, 27.2, 27.3, 27.7, 28.1, 
                 28.3, 28.2, 27.9, 27.6, 27.5, 27.5, 27.6, 28.1, 28.5, 28.6, 28.7, 28.9, 29.3, 
                 29.3, 29.2, 29.2, 29.2, 29.3, 29.6, 29.8, 30.2, 30.2, 29.4, 29.1, 28.8, 29.6, 
                 29.6, 29.6, 28.9, 28.9, 29.3, 29.7, 29.9, 29.8, 29.9, 30.2, 30.3, 29.9, 29.3, 
                 29.2, 29.2, 29.5, 29.7, 29.8, 30, 29.7, 29.6, 29.6, 29.4, 29.3, 29.1, 28.8, 
                 28.8, 28.5, 28.2, 27.8, 26.8, 25.9, 25.7, 25.5, 25.3, 25.2, 25.2, 25.1, 24.9, 
                 24.7, 24.6, 24.4, 24.2, 24, 23.9, 23.7, 23.6, 23.4, 23.4, 23.3, 23.2, 23.2, 
                 23.1, 23.2, 23.1, 23.1, 23, 22.8, 22.7, 22.5, 22.3, 22.1, 22.1, 21.9, 21.9, 
                 21.9, 21.8, 21.8, 21.7, 21.7, 21.6, 21.7, 21.8, 21.9, 21.9, 22, 21.9, 21.8, 
                 21.8, 21.7, 21.6, 21.5, 21.4, 21.4, 21.3, 21.2, 21.2, 21.2, 21.1, 21, 20.9, 
                 20.9, 20.9, 20.9, 20.8, 20.8, 20.8, 20.8, 20.7, 20.7, 20.7, 20.7, 20.7, 20.7, 
                 20.7, 20.7, 20.6, 20.6, 20.5, 20.5, 20.5, 20.4, 20.4, 20.4, 20.4, 20.3, 20.3])

# Coloque o seu código aqui
def calc_hora(posicao):
    h = posicao // 12       # A cada hora são realizadas 12 leituras
    m = (posicao % 12) * 5  # 1 leitura a cada 5 minutos 
    return h,m

tmedia = temp.mean()
print('Temperatura média:', tmedia)
tmaxima = temp.max()
hora,minuto = calc_hora(temp.argmax())
print('Temperatura máxima:', tmaxima, 'efetuadas às ', hora, ':',minuto)
tminima = temp.min()
hora,minuto = calc_hora(temp.argmin())
print('Temperatura mínima:', tminima, 'efetuadas às ', hora, ':',minuto)
var = temp.var()
sd = temp.std()
print('variancia:', var, '\ndesvio-padrão:',sd)
mediana = np.median(temp)
print('Mediana:',mediana)

Temperatura média: 23.49236111111111
Temperatura máxima: 30.3 efetuadas às  15 : 5
Temperatura mínima: 20.1 efetuadas às  3 : 20
variancia: 11.700566647376544 
desvio-padrão: 3.420609104732159
Mediana: 21.9


[voltar ao topo](#top)

<a id="Booleanos"></a> 
### Operadores booleanos

Quando há necessidade de representarmos mais de uma expressão relacional é preciso uní-las através do operadores lógicos (*binário do Python*),  ``&``(E), ``|`` (OU), ``^`` (OU Exlusivo) e ``~``(NÃO).
A combinação de operadores de comparação e operadores booleanos em arrays pode levar a uma ampla gama de operações lógicas eficientes.
Por exemplo, podemos abordar esse tipo de questão composta da seguinte forma:

In [86]:
A = np.array([[1, 2, 3, 4],[5, 6, 7,8]])

# True somente quando os dois são True. Do contrário, False
print((A > 2) & (A < 6))
print("\n")

# False somente quando os dois são False. Do contrário, True
print((A == 2) | (A < 4))
print("\n")

# False quando os dois são False ou True. Do contrário, True
print((A == 2) ^ (A < 4))
print("\n")

# False somente quando True e True quando False.
print(~((A > 2) & (A < 6)))

[[False False  True  True]
 [ True False False False]]


[[ True  True  True False]
 [False False False False]]


[[ True False  True False]
 [False False False False]]


[[ True  True False False]
 [False  True  True  True]]


A tabela a seguir resume os operadores binários booleanos e suss funções equivalentes:<br>


|Operador     |Função equivalente   ||Operador       | Função equivalente  | 
|-------------|---------------------||---------------|---------------------| 
|``&``        |``np.bitwise_and``   || &#124;        |``np.bitwise_or``    | 
|``^``        |``np.bitwise_xor``   ||``~``          |``np.bitwise_not``   | 

<a id="Selecao_Booleana"></a> 
### Seleção em matrizes booleanas
Na seção anterior, analisamos agregados calculados diretamente em matrizes booleanas. Um padrão mais poderoso é usar matrizes booleanas como máscaras, para selecionar subconjuntos específicos dos próprios dados. Como já visto, a obtenção da matriz booleana é feita através de uma expressão relacional sobre a matriz gerando uma matriz booleana. Para *selecionarmos* os valores da matriz, podemos simplesmente indexar esta matriz booleana; isto é conhecido como uma operação *mascaramento*:

In [87]:
arr = np.array([[5, 1, 3, 2], [7, 8, 3, 5], [2, 4, 6, 8]])
print(arr)

[[5 1 3 2]
 [7 8 3 5]
 [2 4 6 8]]


Selecione os elementos maiores ou iguais a 6. 

In [88]:
arr[arr>=6]

array([7, 8, 6, 8])

Selecione os elementos maiores 3 e menores ou iguais a 5. 

In [89]:
arr[(arr > 3) & (arr <= 5)]

array([5, 5, 4])

<a id="Desafio2"></a> 
### <font color="red">Desafio 2 </Font>
O array abaixo exibe os dados meteorológicos históricos (temperatura em ºC e velocidade do vento em Km/h) da região da Basiléia (Suiça) entre os dias 2 e 4 de maio de 2020. As leituras são realizadas em intervalos de 30 minutos a partir da 00:00 hora do dia.
Na Basiléia, até 7ºC a temperatura é considerada *muito fria* e, a partir dos 18ºC, a temperatura é considerada *agradável*.
Utilize o processo de seleção em *matrizes booleanas (mascaramento)* para responder rapidamente as perguntas abaixo:
1. Quantidade de temperaturas considerada agradável?
2. Quantidade de temperaturas considerada muito fria?
3. A temperatura mais alta registrada, dia e a hora em que ocorreu?
4. A temperatura mais baixa registrada, dia e a hora em que ocorreu?
6. Qual a velocidade do vento quando registrou-se a temperatura mais baixa?
7. A velocidade média horária do vento nesses dias?

In [107]:
clima = np.array([[12.240529, 13.056318], [11.640529, 13.628123], [11.310529, 12.74829], [10.820529, 12.0940895],
                  [10.280529, 10.925647], [9.980529, 10.656], [9.840529, 10.669312], [10.030529, 10.137212], 
                  [10.870529, 11.733703], [11.470529, 10.511835], [11.730529, 10.555628], [12.840529, 11.380612],
                  [13.950529, 14.241816], [13.810529, 15.508508], [13.970529, 17.446657], [13.810529, 18.996767],
                  [13.150529, 19.801605], [12.740529, 18.259577], [12.900529, 16.374392], [11.980529, 12.889466], 
                  [11.560529,9.045838], [10.370529, 7.0533133], [9.580529, 6.415762], [8.840529, 6.8491225], 
                  [7.8505287, 6.270311], [6.9705286, 5.5434246], [6.9405284, 4.9121733], [7.540529, 5.7198505], 
                  [6.8805285, 5.986595], [5.6405287, 6.8491225], [5.0705285, 8.262696], [5.2805285, 7.2468624], 
                  [7.8205285, 8.931355], [10.240529, 9.354396], [13.100529, 7.5066204], [15.020529, 2.028842], 
                  [16.22053, 3.5039446], [16.600529, 9.369556], [17.010529, 0.753493], [17.79053, 0.5956885], 
                  [18.350529, 0.5956885], [18.72053, 1.9210378], [19.340528, 4.4097047], [19.080528, 10.403253], 
                  [17.98053, 10.935387], [16.37053, 9.418663], [15.610529, 6.399148], [14.780529, 6.7077804], 
                  [13.560529, 7.539638], [13.160529, 5.9568853], [12.540529, 6.3154216], [12.850529, 4.5833187], 
                  [12.390529, 3.767465], [12.190529, 3.7862556], [12.040529, 4.295571], [12.450529, 3.207881], 
                  [14.210529, 2.1967907], [15.940529, 5.5943995], [17.12053, 5.694981], [17.97053, 7.0078893], 
                  [19.090528, 7.947476], [18.57053, 9.155017], [19.530529, 10.144211], [20.410528, 12.566062], 
                  [20.98053, 13.505193], [21.13053, 15.130956], [21.030529, 13.226431], [20.850529, 10.17913], 
                  [19.64053, 12.01461], [17.240528, 8.599398], [16.30053, 5.651197], [15.140529, 5.328]])

# Coloque seu código aqui
def calc_diahora(posicao):
    d = (posicao // 24) + 2 # Soma 2 porque o primeiro dia é dia 02/05  
    h = posicao % 24      # A cada hora são realizadas 12 leituras
     
    return d,h
cont= np.count_nonzero(clima[:,0] > 18)  # clima[:,0] seleciona toda a coluna 0 - temperatura agradável
print('quantidade de Temperatura agradável:', cont)
cont= np.count_nonzero(clima[:,0] < 7)  # clima[:,0] seleciona toda a coluna 0 - temperatura agradável
print('quantidade de Temperatura muito fria:', cont)
tmaxima = clima[:,0].max()
dia,hora = calc_diahora(clima[:,0].argmax())
print('Temperatura máxima:', tmaxima, 'aconteceu no dia:', dia,'às', hora, ':00')
tminima = clima[:,0].min()
dia,hora = calc_diahora(clima[:,0].argmin())
print('Temperatura mínima:', tminima, 'aconteceu no dia:', dia,'às', hora,  ':00')
velo = clima[clima[:,0].argmin(), 1]
print('Velocidade do vento na mínima:',velo)
vmedia =clima[:,1].mean()
print('Velocidade média do vento:', vmedia)      

quantidade de Temperatura agradável: 13
quantidade de Temperatura muito fria: 6
Temperatura máxima: 21.13053 aconteceu no dia: 4 às 17 :00
Temperatura mínima: 5.0705285 aconteceu no dia: 3 às 6 :00
Velocidade do vento na mínima: 8.262696
Velocidade média do vento: 8.722213391666665


[voltar ao topo](#top)

### <font color="red">FAÇA OS EXERCÍCIOS DA LISTA DE EXERCÍCIOS</font>